ViewModels/DocumentListViewModel.cs
using System.Collections.Generic;
using KVV.DocumentManagement.Models;

namespace KVV.DocumentManagement.ViewModels {
    public class DocumentListViewModel {
        public IList<DocumentGroupPart> Groups { get; set; }
        public int? GroupId { get; set; }
    }
}

ViewModels/DocumentViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using KVV.DocumentManagement.Models;

namespace KVV.DocumentManagement.ViewModels {
    public class DocumentViewModel {
        public IList<DocumentGroupPart> Groups { get; set; }
        public DocumentPart CurrentDocument { get; set; }

        [Required]
        public int? GroupId { get; set; }

        public bool Delete { get; set; }
    }
}

Controllers/DocumentController.cs
using System.Web.Mvc;
using KVV.DocumentManagement.Services;
using Orchard;
using Orchard.ContentManagement;
using Orchard.Environment.Extensions;

namespace KVV.DocumentManagement.Controllers {
    [OrchardFeature("KVV.DocumentManagement")]
    public class DocumentController : ControllerBase {
        private readonly IDocumentManager _documentManager;
        private readonly IOrchardServices _services;
        private readonly IDocumentAuthorizer _documentAuthorizer;
        private dynamic New { get; set; }

        public DocumentController(IDocumentManager documentManager, IOrchardServices services, IDocumentAuthorizer documentAuthorizer) {
            _documentManager = documentManager;
            _services = services;
            _documentAuthorizer = documentAuthorizer;
            New = _services.New;
        }

        public ActionResult Download(int id) {
            var document = _documentManager.Get(id, VersionOptions.Latest);

            if(!_documentAuthorizer.Authorize(document))
                return new HttpUnauthorizedResult();

            var stream = _documentManager.LoadFile(document);
            return File(stream, "application/x-binary", document.OriginalFileName);
        }
    }
}

Views/Parts/Document.cshtml
@using KVV.DocumentManagement.Helpers
@using KVV.DocumentManagement.Models
@{
    Style.Include("file-icons.css");
    var document = (DocumentPart)Model.ContentPart;
}
<p>
    <a class="@document.FileExtension.FileIconClass()" href="@Url.Action("Download", "Document", new { id = document.Id, area = "KVV.DocumentManagement" })">@document.Name</a>
</p>

Views/Parts/DocumentList.AccessDenied.cshtml
<p>@T("Access Denied")</p>

Views/Parts/DocumentList.cshtml
@using KVV.DocumentManagement.Helpers
@using KVV.DocumentManagement.Models
@{
    Style.Include("file-icons.css");
    Style.Include("document-list.css");
    var group = (DocumentGroupPart) Model.DocumentGroup;
    var documents = (IList<DocumentPart>)Model.Documents;
}
<div class="document-list">
    <h1>@group.Name</h1>
    @if (documents.Any()) {
        <ul>
            @foreach (var document in documents) {
                <li><a class="@document.FileExtension.FileIconClass()" href="@Url.ItemDisplayUrl(document)">@document.Name</a></li>
            }
        </ul>
    }
    else {
        <p>@T("There are no documents to display.")</p>
    }
</div>