ViewModels/DocumentGroupViewModel.cs
using System.Collections.Generic;

namespace KVV.DocumentManagement.ViewModels {
    public class DocumentGroupViewModel {
        public IList<DocumentGroupRoleEntry> Roles { get; set; }

        public DocumentGroupViewModel() {
            Roles = new List<DocumentGroupRoleEntry>();
        }
    }

    public class DocumentGroupRoleEntry {
        public string RoleName { get; set; }
        public bool Granted { get; set; }
    }
}

ViewModels/DocumentListViewModel.cs
using System.Collections.Generic;
using KVV.DocumentManagement.Models;

namespace KVV.DocumentManagement.ViewModels {
    public class DocumentListViewModel {
        public IList<DocumentGroupPart> Groups { get; set; }
        public int? GroupId { get; set; }
    }
}

ViewModels/DocumentViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using KVV.DocumentManagement.Models;

namespace KVV.DocumentManagement.ViewModels {
    public class DocumentViewModel {
        public IList<DocumentGroupPart> Groups { get; set; }
        public DocumentPart CurrentDocument { get; set; }

        [Required]
        public int? GroupId { get; set; }

        public bool Delete { get; set; }
    }
}

Controllers/DocumentAdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using KVV.DocumentManagement.Models;
using KVV.DocumentManagement.Services;
using Orchard;
using Orchard.ContentManagement;
using Orchard.Core.Contents.Controllers;
using Orchard.Environment.Extensions;
using Orchard.UI.Admin;
using Orchard.UI.Navigation;
using Orchard.UI.Notify;

namespace KVV.DocumentManagement.Controllers {
    [Admin, OrchardFeature("KVV.DocumentManagement")]
    public class DocumentAdminController : ControllerBase {
        private readonly IDocumentManager _documentManager;
        private readonly IOrchardServices _services;
        private readonly IDocumentGroupManager _documentGroupManager;
        private dynamic New { get; set; }

        public DocumentAdminController(IDocumentManager documentManager, IOrchardServices services, IDocumentGroupManager documentGroupManager) {
            _documentManager = documentManager;
            _services = services;
            _documentGroupManager = documentGroupManager;
            New = _services.New;
        }

        [HttpGet]
        public ActionResult Index(PagerParameters pagerParameters, string q) {
            var pager = new Pager(_services.WorkContext.CurrentSite, pagerParameters);
            var documents = _documentManager.Fetch(VersionOptions.Latest, pager.GetStartIndex(), pager.PageSize, q).ToList();
            var count = _documentManager.Count(VersionOptions.Latest, q);
            var model = New.ViewModel(
                DocumentGroups: _documentGroupManager.Fetch().ToList(),
                Documents: documents.Select(x => New.Document(
                    Content: x,
                    Id: x.Id,
                    Title: x.Name,
                    Url: x.Url,
                    Created: x.Created,
                    Modified: x.Modified,
                    User: x.User,
                    Group: x.Group,
                    IDocumentGroupManager: x.Group,
                    IsPublished: x.IsPublished())).ToList(),
                SearchTerm: q,
                Pager: New.Pager(pager).TotalItemCount(count)
            );
            return View(model);
        }

        [FormValueRequired("submit.Search"), HttpPost, ActionName("Index")]
        public ActionResult Search(PagerParameters pagerParameters, string q) {
            return RedirectToAction("Index", new {page = pagerParameters.Page, pageSize = pagerParameters.PageSize, q});
        }

        [FormValueRequired("submit.AssignGroup"), HttpPost, ActionName("Index")]
        public ActionResult AssignGroup(PagerParameters pagerParameters, IEnumerable<int> documentIds, int? groupId) {

            if(groupId == null)
                _services.Notifier.Error(T("Please select a group."));

            if(documentIds == null)
                _services.Notifier.Error(T("Please check the documents that you want the group to assign to."));

            if (groupId != null && documentIds != null) {
                var documents = _services.ContentManager.GetMany<DocumentPart>(documentIds, VersionOptions.Latest, QueryHints.Empty).ToList();
                var group = _services.ContentManager.Get<DocumentGroupPart>(groupId.Value);
                _documentManager.AssignGroup(documents, group);
                _services.Notifier.Information(T("The selected documents have been assigned to the {0} group.", group.Name));
            }

            return RedirectToAction("Index", new { page = pagerParameters.Page, pageSize = pagerParameters.PageSize});
        }

        public ActionResult Delete(int id) {
            var document = _documentManager.Get(id, VersionOptions.Latest);
            _documentManager.Delete(document);
            _services.Notifier.Information(T("The {0} document has been removed.", document.Name));
            return RedirectToAction("Index");
        }

        public ActionResult Download(int id) {
            var document = _documentManager.Get(id, VersionOptions.Latest);
            var stream = _documentManager.LoadFile(document);
            return File(stream, "application/x-binary", document.OriginalFileName);
        }

        public ActionResult Publish(int id) {
            var document = _documentManager.Get(id, VersionOptions.Draft);
            _documentManager.Publish(document);
            _services.Notifier.Information(T("The {0} document has been successfully published.", document.Name));
            return RedirectToAction("Index");
        }

        public ActionResult Unpublish(int id) {
            var document = _documentManager.Get(id, VersionOptions.Published);
            _documentManager.Unpublish(document);
            _services.Notifier.Information(T("The {0} document has been successfully unpublished.", document.Name));
            return RedirectToAction("Index");
        }
    }
}

Controllers/DocumentController.cs
using System.Web.Mvc;
using KVV.DocumentManagement.Services;
using Orchard;
using Orchard.ContentManagement;
using Orchard.Environment.Extensions;

namespace KVV.DocumentManagement.Controllers {
    [OrchardFeature("KVV.DocumentManagement")]
    public class DocumentController : ControllerBase {
        private readonly IDocumentManager _documentManager;
        private readonly IOrchardServices _services;
        private readonly IDocumentAuthorizer _documentAuthorizer;
        private dynamic New { get; set; }

        public DocumentController(IDocumentManager documentManager, IOrchardServices services, IDocumentAuthorizer documentAuthorizer) {
            _documentManager = documentManager;
            _services = services;
            _documentAuthorizer = documentAuthorizer;
            New = _services.New;
        }

        public ActionResult Download(int id) {
            var document = _documentManager.Get(id, VersionOptions.Latest);

            if(!_documentAuthorizer.Authorize(document))
                return new HttpUnauthorizedResult();

            var stream = _documentManager.LoadFile(document);
            return File(stream, "application/x-binary", document.OriginalFileName);
        }
    }
}

Views/EditorTemplates/Parts/Document.cshtml
@using KVV.DocumentManagement.Helpers
@model KVV.DocumentManagement.ViewModels.DocumentViewModel
@{
    Script.Require("jQuery");
    Style.Include("file-icons.css");
    Style.Include("document-editor-admin.css");
    Script.Include("document-editor-admin.js");
    
    var options = Model.Groups.Select(x => new SelectListItem {Text = x.Name, Value = x.Id.ToString(), Selected = x.Id == Model.GroupId}).ToList();
    var currentFileExtension = Model.CurrentDocument.FileExtension;
    var hasFile = !string.IsNullOrWhiteSpace(Model.CurrentDocument.OriginalFileName) && !Model.Delete;
    var fileIconClass = currentFileExtension.FileIconClass();
}
<fieldset class="document-editor">
    @Html.HiddenFor(m => m.Delete, new { @class = "document-deleted" })
    @if (hasFile) {
        <div class="current-file-wrapper group">
            <label>@T("Current File")</label>
            <a class="@fileIconClass" href="@Url.Action("Download", "DocumentAdmin", new { area = "KVV.DocumentManagement", id = Model.CurrentDocument.Id })">@Model.CurrentDocument.OriginalFileName</a>
            <a class="delete-file" href="#" title="@T("Delete")" data-prompt="@T("The file will be permanently deleted after publishing this document. Are you sure you wish to continue?")"></a>
        </div>
    }
    <div>
        <label for="DocumentFile">@T("Document")</label>
        <input type="file" id="DocumentFile" name="DocumentFile"/>
        @if (hasFile) {
            <div class="hint">@T("Uploading a file will overwrite the current one")</div>
        }
        else {
            <div class="hint">@T("Upload a file for this document")</div>
        }
    </div>
</fieldset>

<fieldset>
    <div>
        <label for="@Html.FieldIdFor(m => m.GroupId)">@T("Group")</label>
        @Html.DropDownListFor(m => m.GroupId, options, "")
    </div>
</fieldset>

Views/EditorTemplates/Parts/DocumentGroup.cshtml
@model KVV.DocumentManagement.ViewModels.DocumentGroupViewModel

<fieldset>
    <legend>@T("Roles")</legend>
    @if (Model.Roles.Count > 0) {
        var index = 0;
        foreach (var entry in Model.Roles) {
            @Html.Hidden("Roles[" + index + "].RoleName", entry.RoleName)

    <div>
        @Html.CheckBox("Roles[" + index + "].Granted", entry.Granted)
        <label class="forcheckbox" for="@Html.FieldIdFor(m => m.Roles[index].Granted)">@entry.RoleName</label>
    </div>
            index++;
        }
    }
    else {
    <p>@T("There are no roles.")</p>
    }
</fieldset>

Views/EditorTemplates/Parts/DocumentList.cshtml
@model KVV.DocumentManagement.ViewModels.DocumentListViewModel
@{
    var options = Model.Groups.Select(x => new SelectListItem {Text = x.Name, Value = x.Id.ToString(), Selected = x.Id == Model.GroupId}).ToList();
}
<fieldset>
    <legend>@T("Documents")</legend>
    <div>
        <label for="@Html.FieldIdFor(m => m.GroupId)">@T("Group")</label>
        @Html.DropDownListFor(m => m.GroupId, options, "")
    </div>
</fieldset>

Views/EditorTemplates/Parts/DocumentsSettings.cshtml
@model KVV.DocumentManagement.Models.DocumentsSettingsPartRecord
<fieldset>
    <legend>@T("Document Storage Settings")</legend>
    <div>
        @Html.LabelFor(m => m.DocumentsPath, T("Documents Path"))
        @Html.TextBoxFor(m => m.DocumentsPath, new { @class = "text large" })
        @Html.ValidationMessageFor(m => m.DocumentsPath, "*")
        <div class="hint">@T("The relative path where the uploaded documents should be stored.")</div>
    </div>
</fieldset>